[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
arising = "GT1koQQwD6ZV6bxciNSwC3YFDHiByySKZbQ2MQJF4GWp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
