[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
arising = "8eRLNRfCsDbAgXuFSHufEjeM1VJEYZGCtSoS9WZmfKZD"

[programs.mainnet]
arising = "8eRLNRfCsDbAgXuFSHufEjeM1VJEYZGCtSoS9WZmfKZD"

[provider]
cluster = "devnet"
wallet = "./arising-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
