name: Test
'on': push
jobs:
    anchor-test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/eabz/docker-solana-anchor:main
        steps:
            - uses: actions/checkout@v3
            - name: Cache Build
              id: arising-build
              uses: actions/cache@v3
              with:
                  path: target
                  key: "${{ hashFiles('./Cargo.lock') }}-arising"
            - name: Set Anchor
              run: avm install latest && avm use latest
            - name: Build
              run: yarn build
