name: Test

on: push

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Solana
        run: | 
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"       
      - name: Cache Build
        id: arising-build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ hashFiles(Cargo.lock) }}-arising          


